### ISSUE TITLE
snafu-derive 0.4.2 broke `#[doc(hidden)]`

### ISSUE THREAD

**Issue by jgallagher** [shepmaster/snafu#139] opened 2019-08-07 02:04 UTC
Hi - big fan of snafu! I have a crate that depends on it, and it looks like I'm getting bit by a backwards-incompatible change in a patch release in snafu (jgallagher/amiquip#12). Specifically, [this code](https://github.com/jgallagher/amiquip/blob/c81c49a5c6ded91c3a8e2816a85c0e2c138b4614/src/errors.rs#L250-L252) compiles if I download snafu 0.4.1 and change its snafu-derive dependency to `"=0.4.1"`, but breaks if it's `"0.4.1"` (the published value) or `"=0.4.2"`.

I looked at the issues and didn't see anyone else mention this, so maybe I'm the only one that got bit by it. I'm about to publish a patch release that just removes the `#[doc(hidden)]` attribute for now, but I am curious if it's still possible to include it somehow with 0.4.3.

**Comment by mikeando** [comment] 2019-08-07 02:15
Hi John,

Can I suggest that you create a minimal reproducer - I think it would be trivial, but I've not got rust available at the moment, so can't whip one up myself.

That way there will be something simple for developers to turn into a real test and work out where to go from there.

**Comment by jgallagher** [comment] 2019-08-07 02:30
Sure, although it's basically just what I linked to:

```rust
#[derive(Debug, Snafu)]
enum Error {
    #[doc(hidden)]
    #[snafu(display("demo"))]
    Demo,
}
```

does not compile with any currently-published version of snafu 0.4.x, but did compile on 0.4.1 before 0.4.2 was published.

**Comment by shepmaster** [comment] 2019-08-07 02:38
I have a hunch that this is due to https://github.com/shepmaster/snafu/pull/107, specifically [in this code](https://github.com/shepmaster/snafu/blob/0.4.2/snafu-derive/src/lib.rs#L598-L608).

One "tricky" thing about this patch is that we have some backwards incompatible changes brewing in master. However, #136 *also* is ready to go, so I might need to set up a branch for 0.4 and land both this fix and that enhancement for 0.4.4.

**Comment by shepmaster** [comment] 2019-08-07 03:03
It would be good for you to show the error message that you get. This ensures that what we reproduce matches your behavior.

**Comment by shepmaster** [comment] 2019-08-07 12:12
@jgallagher do you think you can test your local code with #143? I believe that will fix it.

**Comment by shepmaster** [comment] 2019-08-07 14:16
Released as SNAFU 0.4.4

**Closed** 2019-08-07 14:26 UTC
Labels: bug, found in the field, good first issue

**Comment by jgallagher** [comment] 2019-08-07 23:51
@shepmaster Sorry for the delay, can't usually respond during the day. Yep, this did fix it. The error I was getting was

```
error: expected `=`
 --> src/main.rs:5:10
  |
5 |     #[doc(hidden)]
  |          ^^^^^^^^

error: aborting due to previous error
```

Thanks for the super fast fix!

**Comment by shepmaster** [comment] 2019-08-07 23:55
No worries; sorry for any trouble we caused!
