### ISSUE TITLE
Consider enabling autoconverstions without context.

### ISSUE THREAD

**Issue by dpc** [shepmaster/snafu#90] opened 2019-06-03 23:31 UTC
Sometimes there is no context and every error type maps directly to a given snafu-error variant. It would be great if there was a way to support it in the macro.

**Comment by shepmaster** [comment] 2019-06-10 01:02
Duplicate of #78; would appreciate [feedback and suggestions on a potential syntax](https://github.com/shepmaster/snafu/issues/78#issuecomment-493641113).

**Closed by shepmaster** 2019-06-10 01:02 UTC
