### ISSUE TITLE
Does not play nicely with Mutex and lifetimes

### ISSUE THREAD

**Issue by TheAifam5** [shepmaster/snafu#236] opened 2020-05-11 18:54 UTC
Hey,
is there a way to use `Mutex` with snafu? The `MutexGuard` requires lifetime parameter. That applies to other error types too. Defining lifetime parameter to my error declaration does not work too.

Environment:
- Rust: rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
- Cargo: cargo 1.45.0-nightly (f534844c2 2020-05-06)
- snafu: 0.6.7

Repro, I know I should not set the `'static` lifetime there:
```rust
#![warn(rust_2018_idioms)]

use snafu::{Backtrace, Snafu};
use std::sync::{Mutex, MutexGuard, PoisonError};

#[derive(Debug, Snafu)]
pub enum ReproError {
  #[snafu(context(false))]
  OutgoingPoisoned { source: PoisonError<MutexGuard<'static, Vec<Vec<u8>>>>, backtrace: Backtrace },
}

type Result<T, E = ReproError> = std::result::Result<T, E>;

pub struct Repro {
  outgoing: Mutex<Vec<Vec<u8>>>,
}

impl Repro {
  fn do_action(&mut self) -> Result<()> {
    self.outgoing.lock()?; // now you can like iterate through,
                           // send all packets, clear outgoing and unlock
    Ok(())
  }
}
```

Error message:
```
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
  --> src/reprod.rs:18:19
   |
18 |     self.outgoing.lock()?;
   |                   ^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 17:3...
  --> src/reprod.rs:17:3
   |
17 | /   fn do_action(&mut self) -> Result<()> {
18 | |     self.outgoing.lock()?;
19 | |     Ok(())
20 | |   }
   | |___^
note: ...so that reference does not outlive borrowed content
  --> src/reprod.rs:18:5
   |
18 |     self.outgoing.lock()?;
   |     ^^^^^^^^^^^^^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the types are compatible
  --> src/reprod.rs:18:25
   |
18 |     self.outgoing.lock()?;
   |                         ^
   = note: expected  `std::convert::From<std::sync::PoisonError<std::sync::MutexGuard<'_, std::vec::Vec<std::vec::Vec<u8>>>>>`
              found  `std::convert::From<std::sync::PoisonError<std::sync::MutexGuard<'static, std::vec::Vec<std::vec::Vec<u8>>>>>`
```

Regards,
TheAifam5

**Comment by shepmaster** [comment] 2020-05-11 18:58
Please have the respect to provide a **complete** and **minimal** example that demonstrates the problem you are having. The code you have provided doesn't show the imported types, nor do you specify what version of SNAFU you are using. Without that, I have to take an inordinate amount of time to reproduce the problem myself.

**Comment by TheAifam5** [comment] 2020-05-11 19:05
Updated, with repro code.

**Comment by shepmaster** [comment] 2020-05-11 19:53
I think this is a duplicate of #99. The code that you *should* be able to write is:

```rust
#[derive(Debug, Snafu)]
pub enum ReproError<'a> {
    #[snafu(context(false))]
    OutgoingPoisoned {
        source: PoisonError<MutexGuard<'a, Vec<Vec<u8>>>>,
        backtrace: Backtrace,
    },
}

type Result<'a, T, E = ReproError<'a>> = std::result::Result<T, E>;
```

```rust
impl Repro {
    fn do_action(&mut self) -> Result<'_, ()> {
        self.outgoing.lock()?; 
        Ok(())
    }
}
```

This almost works, but we cannot implement `std::error::Error::source` due to its requirement of `'static`:

```rust
fn source(&self) -> Option<&(dyn snafu::Error + 'static)> {
//                                              ^^^^^^^
```

**Comment by shepmaster** [comment] 2021-05-04 00:12
duplicate of #99

**Closed by shepmaster** 2021-05-04 00:12 UTC
