### ISSUE TITLE
Need a way to incorporate i18n behaviors in display

### ISSUE THREAD

**Issue by kesmit13** [shepmaster/snafu#283] opened 2021-04-29 20:55 UTC
The `display(...)` directive in snafu accepts a particular format of string for doing formatted substitutions. Is there a way to incorporate translated strings in this? Having a way to integrate with something like [fluent](https://docs.rs/fluent/0.15.0/fluent/index.html) where the substitution variable map could be generated automatically would be ideal. Maybe there is a way to override the display method in snafu that I just haven't seen yet.

**Comment by shepmaster** [comment] 2021-04-29 23:41
See also https://github.com/projectfluent/fluent-rs/issues/107

**Comment by kesmit13** [comment] 2021-04-30 00:05
Yep, that's almost exactly what I was thinking.

**Comment by shepmaster** [comment] 2021-05-03 12:52
Closing as duplicate of #254

**Closed by shepmaster** 2021-05-03 12:52 UTC
Labels: enhancement, help wanted

**Comment by kesmit13** [comment] 2021-05-03 18:31
So is there any way to currently use something other than a string literal as an error message?

**Comment by shepmaster** [comment] 2021-05-03 18:47
There is not.
